port : "8083"

db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "postgres"

email:
  host: "smtp.gmail.com"
  port: 587
  username: "gwynbleiddeducourse@gmail.com"
  password: "ppgarwpwchflcyvk"