services:
  frontend:
    build: frontend
    ports:
      - "2001:80"
    networks:
      - app-network

  backend1:
    build: ./backend
    ports:
      - "8083:8083"

    networks:
      - app-network
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend1.rule=Host(`backend1.195.133.20.34`)"
      - "traefik.http.services.backend1.loadbalancer.server.port=8083"

  backend2:
    build: ./backend
    ports:
      - "8084:8083"
    networks:
      - app-network
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend2.rule=Host(`backend2.195.133.20.34`)"
      - "traefik.http.services.backend2.loadbalancer.server.port=8083"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-init/init.up.sql:/docker-entrypoint-initdb.d/init_up.sql
    networks:
      - app-network

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "8080:80"
      - "80:8080"
    networks:
      - app-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
